# Generated by Django 4.0.6 on 2022-07-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinorTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('read_more', models.CharField(max_length=200)),
                ('vid_url', models.CharField(max_length=200)),
                ('offered_by', models.CharField(max_length=100)),
                ('tot_creds', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
