# Generated by Django 4.0.6 on 2022-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_minortrack_read_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minortrack',
            name='icon_class',
            field=models.CharField(default='fa-shopping-bag', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minortrack',
            name='syllabus',
            field=models.FileField(default='', upload_to='pdfs'),
            preserve_default=False,
        ),
    ]
