# Generated by Django 4.0.6 on 2022-07-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_minortrack_icon_class_minortrack_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('course_code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('lec', models.PositiveSmallIntegerField()),
                ('creds', models.PositiveSmallIntegerField()),
                ('mt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.minortrack')),
            ],
        ),
    ]
